// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZooManagement;

#nullable disable

namespace ZooManagement.Migrations
{
    [DbContext(typeof(Zoo))]
    [Migration("20240307151441_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfAcquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            DateOfAcquisition = new DateTime(1999, 12, 31, 18, 30, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 10, 15, 18, 30, 0, 0, DateTimeKind.Utc),
                            Name = "simba",
                            Sex = 0,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -2,
                            DateOfAcquisition = new DateTime(2001, 2, 2, 18, 30, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1997, 9, 9, 18, 30, 0, 0, DateTimeKind.Utc),
                            Name = "nala",
                            Sex = 1,
                            SpeciesId = -1
                        },
                        new
                        {
                            Id = -20,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6550),
                            DateOfBirth = new DateTime(2017, 1, 6, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6540),
                            Name = "animal_20",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -21,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6568),
                            DateOfBirth = new DateTime(2018, 6, 29, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6568),
                            Name = "animal_21",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -22,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6582),
                            DateOfBirth = new DateTime(2019, 7, 23, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6581),
                            Name = "animal_22",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -23,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6599),
                            DateOfBirth = new DateTime(2020, 11, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6599),
                            Name = "animal_23",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -24,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6612),
                            DateOfBirth = new DateTime(2017, 9, 6, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6611),
                            Name = "animal_24",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -25,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6624),
                            DateOfBirth = new DateTime(2022, 5, 1, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6623),
                            Name = "animal_25",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -26,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6688),
                            DateOfBirth = new DateTime(2021, 9, 22, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6688),
                            Name = "animal_26",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -27,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6704),
                            DateOfBirth = new DateTime(2019, 6, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6703),
                            Name = "animal_27",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -28,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6717),
                            DateOfBirth = new DateTime(2017, 11, 11, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6717),
                            Name = "animal_28",
                            Sex = 1,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -29,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6730),
                            DateOfBirth = new DateTime(2018, 2, 16, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6730),
                            Name = "animal_29",
                            Sex = 0,
                            SpeciesId = -2
                        },
                        new
                        {
                            Id = -30,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6768),
                            DateOfBirth = new DateTime(2016, 2, 9, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6767),
                            Name = "animal_30",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -31,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6781),
                            DateOfBirth = new DateTime(2019, 7, 21, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6780),
                            Name = "animal_31",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -32,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6794),
                            DateOfBirth = new DateTime(2020, 7, 23, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6794),
                            Name = "animal_32",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -33,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6808),
                            DateOfBirth = new DateTime(2023, 2, 25, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6807),
                            Name = "animal_33",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -34,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6819),
                            DateOfBirth = new DateTime(2019, 6, 26, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6819),
                            Name = "animal_34",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -35,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6832),
                            DateOfBirth = new DateTime(2017, 10, 23, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6831),
                            Name = "animal_35",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -36,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6843),
                            DateOfBirth = new DateTime(2024, 1, 1, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6842),
                            Name = "animal_36",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -37,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6854),
                            DateOfBirth = new DateTime(2023, 12, 3, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6854),
                            Name = "animal_37",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -38,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6867),
                            DateOfBirth = new DateTime(2021, 4, 17, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6867),
                            Name = "animal_38",
                            Sex = 1,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -39,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6879),
                            DateOfBirth = new DateTime(2021, 12, 30, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6878),
                            Name = "animal_39",
                            Sex = 0,
                            SpeciesId = -3
                        },
                        new
                        {
                            Id = -40,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6903),
                            DateOfBirth = new DateTime(2024, 1, 25, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6903),
                            Name = "animal_40",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -41,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6915),
                            DateOfBirth = new DateTime(2021, 10, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6915),
                            Name = "animal_41",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -42,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6929),
                            DateOfBirth = new DateTime(2020, 6, 14, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6928),
                            Name = "animal_42",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -43,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6941),
                            DateOfBirth = new DateTime(2021, 8, 31, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6940),
                            Name = "animal_43",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -44,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6952),
                            DateOfBirth = new DateTime(2023, 7, 13, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6951),
                            Name = "animal_44",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -45,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6964),
                            DateOfBirth = new DateTime(2015, 12, 24, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6963),
                            Name = "animal_45",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -46,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6976),
                            DateOfBirth = new DateTime(2023, 12, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(6975),
                            Name = "animal_46",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -47,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7052),
                            DateOfBirth = new DateTime(2022, 7, 17, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7051),
                            Name = "animal_47",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -48,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7065),
                            DateOfBirth = new DateTime(2023, 11, 6, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7064),
                            Name = "animal_48",
                            Sex = 1,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -49,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7078),
                            DateOfBirth = new DateTime(2024, 2, 26, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7077),
                            Name = "animal_49",
                            Sex = 0,
                            SpeciesId = -4
                        },
                        new
                        {
                            Id = -50,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7105),
                            DateOfBirth = new DateTime(2019, 10, 15, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7104),
                            Name = "animal_50",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -51,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7119),
                            DateOfBirth = new DateTime(2021, 2, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7118),
                            Name = "animal_51",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -52,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7130),
                            DateOfBirth = new DateTime(2023, 11, 5, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7130),
                            Name = "animal_52",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -53,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7142),
                            DateOfBirth = new DateTime(2021, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7142),
                            Name = "animal_53",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -54,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7155),
                            DateOfBirth = new DateTime(2022, 5, 14, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7154),
                            Name = "animal_54",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -55,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7166),
                            DateOfBirth = new DateTime(2019, 2, 4, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7166),
                            Name = "animal_55",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -56,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7179),
                            DateOfBirth = new DateTime(2021, 7, 2, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7179),
                            Name = "animal_56",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -57,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7191),
                            DateOfBirth = new DateTime(2021, 11, 13, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7191),
                            Name = "animal_57",
                            Sex = 1,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -58,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7204),
                            DateOfBirth = new DateTime(2018, 5, 2, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7204),
                            Name = "animal_58",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -59,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7216),
                            DateOfBirth = new DateTime(2017, 1, 13, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7216),
                            Name = "animal_59",
                            Sex = 0,
                            SpeciesId = -5
                        },
                        new
                        {
                            Id = -60,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7241),
                            DateOfBirth = new DateTime(2017, 7, 23, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7240),
                            Name = "animal_60",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -61,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7255),
                            DateOfBirth = new DateTime(2016, 10, 15, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7254),
                            Name = "animal_61",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -62,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7266),
                            DateOfBirth = new DateTime(2021, 8, 14, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7266),
                            Name = "animal_62",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -63,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7278),
                            DateOfBirth = new DateTime(2019, 11, 17, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7277),
                            Name = "animal_63",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -64,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7288),
                            DateOfBirth = new DateTime(2022, 9, 3, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7288),
                            Name = "animal_64",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -65,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7300),
                            DateOfBirth = new DateTime(2020, 3, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7300),
                            Name = "animal_65",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -66,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7312),
                            DateOfBirth = new DateTime(2017, 7, 3, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7312),
                            Name = "animal_66",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -67,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7373),
                            DateOfBirth = new DateTime(2023, 10, 4, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7373),
                            Name = "animal_67",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -68,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7387),
                            DateOfBirth = new DateTime(2022, 6, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7386),
                            Name = "animal_68",
                            Sex = 0,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -69,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7399),
                            DateOfBirth = new DateTime(2020, 12, 28, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7399),
                            Name = "animal_69",
                            Sex = 1,
                            SpeciesId = -6
                        },
                        new
                        {
                            Id = -70,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7429),
                            DateOfBirth = new DateTime(2018, 7, 2, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7428),
                            Name = "animal_70",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -71,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7440),
                            DateOfBirth = new DateTime(2017, 2, 11, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7440),
                            Name = "animal_71",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -72,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7453),
                            DateOfBirth = new DateTime(2021, 9, 15, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7452),
                            Name = "animal_72",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -73,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7465),
                            DateOfBirth = new DateTime(2016, 8, 23, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7465),
                            Name = "animal_73",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -74,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7477),
                            DateOfBirth = new DateTime(2017, 1, 24, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7476),
                            Name = "animal_74",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -75,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7489),
                            DateOfBirth = new DateTime(2023, 11, 4, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7488),
                            Name = "animal_75",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -76,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7501),
                            DateOfBirth = new DateTime(2022, 10, 10, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7500),
                            Name = "animal_76",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -77,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7512),
                            DateOfBirth = new DateTime(2022, 10, 19, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7511),
                            Name = "animal_77",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -78,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7523),
                            DateOfBirth = new DateTime(2021, 9, 13, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7522),
                            Name = "animal_78",
                            Sex = 1,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -79,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7535),
                            DateOfBirth = new DateTime(2021, 1, 2, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7535),
                            Name = "animal_79",
                            Sex = 0,
                            SpeciesId = -7
                        },
                        new
                        {
                            Id = -80,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7560),
                            DateOfBirth = new DateTime(2018, 6, 10, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7559),
                            Name = "animal_80",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -81,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7572),
                            DateOfBirth = new DateTime(2016, 4, 22, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7572),
                            Name = "animal_81",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -82,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7585),
                            DateOfBirth = new DateTime(2021, 4, 28, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7584),
                            Name = "animal_82",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -83,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7597),
                            DateOfBirth = new DateTime(2018, 5, 29, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7596),
                            Name = "animal_83",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -84,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7608),
                            DateOfBirth = new DateTime(2021, 6, 13, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7608),
                            Name = "animal_84",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -85,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7621),
                            DateOfBirth = new DateTime(2022, 10, 9, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7620),
                            Name = "animal_85",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -86,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7668),
                            DateOfBirth = new DateTime(2022, 8, 16, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7667),
                            Name = "animal_86",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -87,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7681),
                            DateOfBirth = new DateTime(2019, 12, 9, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7680),
                            Name = "animal_87",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -88,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7693),
                            DateOfBirth = new DateTime(2023, 9, 29, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7692),
                            Name = "animal_88",
                            Sex = 1,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -89,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7705),
                            DateOfBirth = new DateTime(2020, 7, 27, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7705),
                            Name = "animal_89",
                            Sex = 0,
                            SpeciesId = -8
                        },
                        new
                        {
                            Id = -90,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7733),
                            DateOfBirth = new DateTime(2022, 4, 27, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7732),
                            Name = "animal_90",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -91,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7745),
                            DateOfBirth = new DateTime(2017, 2, 5, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7744),
                            Name = "animal_91",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -92,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7757),
                            DateOfBirth = new DateTime(2022, 12, 1, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7756),
                            Name = "animal_92",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -93,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7771),
                            DateOfBirth = new DateTime(2022, 1, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7770),
                            Name = "animal_93",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -94,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7782),
                            DateOfBirth = new DateTime(2021, 4, 4, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7782),
                            Name = "animal_94",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -95,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7794),
                            DateOfBirth = new DateTime(2022, 11, 16, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7794),
                            Name = "animal_95",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -96,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7807),
                            DateOfBirth = new DateTime(2024, 1, 19, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7806),
                            Name = "animal_96",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -97,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7818),
                            DateOfBirth = new DateTime(2020, 9, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7818),
                            Name = "animal_97",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -98,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7829),
                            DateOfBirth = new DateTime(2019, 8, 26, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7828),
                            Name = "animal_98",
                            Sex = 0,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -99,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7840),
                            DateOfBirth = new DateTime(2019, 6, 5, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7840),
                            Name = "animal_99",
                            Sex = 1,
                            SpeciesId = -9
                        },
                        new
                        {
                            Id = -100,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7867),
                            DateOfBirth = new DateTime(2020, 5, 10, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7866),
                            Name = "animal_100",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -101,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7879),
                            DateOfBirth = new DateTime(2016, 12, 31, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7878),
                            Name = "animal_101",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -102,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7891),
                            DateOfBirth = new DateTime(2019, 7, 26, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7891),
                            Name = "animal_102",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -103,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7904),
                            DateOfBirth = new DateTime(2021, 11, 15, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7903),
                            Name = "animal_103",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -104,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7917),
                            DateOfBirth = new DateTime(2021, 1, 26, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7916),
                            Name = "animal_104",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -105,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7928),
                            DateOfBirth = new DateTime(2020, 7, 17, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7928),
                            Name = "animal_105",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -106,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7940),
                            DateOfBirth = new DateTime(2020, 6, 24, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7939),
                            Name = "animal_106",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -107,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7951),
                            DateOfBirth = new DateTime(2021, 8, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7950),
                            Name = "animal_107",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -108,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7999),
                            DateOfBirth = new DateTime(2021, 8, 17, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(7999),
                            Name = "animal_108",
                            Sex = 1,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -109,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8013),
                            DateOfBirth = new DateTime(2017, 9, 10, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8012),
                            Name = "animal_109",
                            Sex = 0,
                            SpeciesId = -10
                        },
                        new
                        {
                            Id = -110,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8042),
                            DateOfBirth = new DateTime(2019, 8, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8041),
                            Name = "animal_110",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -111,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8054),
                            DateOfBirth = new DateTime(2022, 11, 8, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8053),
                            Name = "animal_111",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -112,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8066),
                            DateOfBirth = new DateTime(2018, 10, 4, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8066),
                            Name = "animal_112",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -113,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8078),
                            DateOfBirth = new DateTime(2022, 4, 13, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8077),
                            Name = "animal_113",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -114,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8090),
                            DateOfBirth = new DateTime(2016, 9, 2, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8089),
                            Name = "animal_114",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -115,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8102),
                            DateOfBirth = new DateTime(2019, 3, 15, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8101),
                            Name = "animal_115",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -116,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8114),
                            DateOfBirth = new DateTime(2020, 12, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8114),
                            Name = "animal_116",
                            Sex = 0,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -117,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8126),
                            DateOfBirth = new DateTime(2017, 11, 24, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8126),
                            Name = "animal_117",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -118,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8138),
                            DateOfBirth = new DateTime(2022, 5, 29, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8137),
                            Name = "animal_118",
                            Sex = 1,
                            SpeciesId = -11
                        },
                        new
                        {
                            Id = -119,
                            DateOfAcquisition = new DateTime(2024, 3, 7, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8150),
                            DateOfBirth = new DateTime(2016, 4, 12, 15, 14, 41, 305, DateTimeKind.Utc).AddTicks(8149),
                            Name = "animal_119",
                            Sex = 0,
                            SpeciesId = -11
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Classification")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Species");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Classification = 0,
                            Name = "lion"
                        },
                        new
                        {
                            Id = -2,
                            Classification = 2,
                            Name = "species_2"
                        },
                        new
                        {
                            Id = -3,
                            Classification = 5,
                            Name = "species_3"
                        },
                        new
                        {
                            Id = -4,
                            Classification = 1,
                            Name = "species_4"
                        },
                        new
                        {
                            Id = -5,
                            Classification = 3,
                            Name = "species_5"
                        },
                        new
                        {
                            Id = -6,
                            Classification = 1,
                            Name = "species_6"
                        },
                        new
                        {
                            Id = -7,
                            Classification = 5,
                            Name = "species_7"
                        },
                        new
                        {
                            Id = -8,
                            Classification = 2,
                            Name = "species_8"
                        },
                        new
                        {
                            Id = -9,
                            Classification = 4,
                            Name = "species_9"
                        },
                        new
                        {
                            Id = -10,
                            Classification = 2,
                            Name = "species_10"
                        },
                        new
                        {
                            Id = -11,
                            Classification = 1,
                            Name = "species_11"
                        });
                });

            modelBuilder.Entity("ZooManagement.Models.Data.Animal", b =>
                {
                    b.HasOne("ZooManagement.Models.Data.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
